services:
  sfss_headless_cli:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: sfss_headless_cli
    volumes:
      - .:/root/code
    # Necessary security capabilities for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
